version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db-laravel
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
      - ./mysql-backup:/var/lib/mysql-backup

volumes:
  db_data:
